# Generated by Django 3.2.12 on 2022-02-13 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('Id_Medico', models.BigAutoField(primary_key=True, serialize=False)),
                ('CPF', models.IntegerField()),
                ('Nome', models.CharField(max_length=255)),
                ('Idade', models.IntegerField()),
                ('Sexo', models.CharField(default='?', max_length=1)),
                ('Especialidade', models.CharField(max_length=255)),
                ('CEP', models.IntegerField()),
                ('Endereco', models.CharField(max_length=255)),
                ('Usuario', models.CharField(max_length=255, unique=True)),
                ('Token', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('Id_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('CPF', models.IntegerField()),
                ('Nome', models.CharField(max_length=255)),
                ('Idade', models.IntegerField()),
                ('Sexo', models.CharField(default='?', max_length=1)),
                ('Comorbidades', models.CharField(blank=True, max_length=255)),
                ('CEP', models.IntegerField()),
                ('Endereco', models.CharField(max_length=255)),
                ('Responsavel', models.CharField(blank=True, max_length=255)),
                ('Telefone_Responsavel', models.IntegerField(blank=True)),
                ('Usuario', models.CharField(max_length=255, unique=True)),
                ('Token', models.CharField(blank=True, max_length=45)),
                ('Id_Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('Id_Sensor', models.BigAutoField(primary_key=True, serialize=False)),
                ('Id_Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
                ('Id_Paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('Id_Sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.sensor')),
                ('Temperatura', models.FloatField(blank=True, max_length=10)),
                ('Pressao', models.FloatField(blank=True, max_length=10)),
                ('Oxigenacao', models.FloatField(blank=True, max_length=10)),
                ('Frequencia_Cardiaca', models.FloatField(blank=True, max_length=10)),
                ('Data_Hora', models.DateTimeField()),
            ],
        ),
    ]
