# Generated by Django 4.0.2 on 2022-02-14 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dados',
            name='Id_Sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor'),
        ),
    ]
