# Generated by Django 4.0.2 on 2022-02-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Telefone_Responsavel',
            field=models.IntegerField(blank=True),
        ),
    ]
