# Generated by Django 3.2.12 on 2022-02-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='Email',
            field=models.CharField(default='?', max_length=255),
        ),
        migrations.AddField(
            model_name='medico',
            name='Telefone',
            field=models.CharField(default='?', max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Email',
            field=models.CharField(default='?', max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Telefone',
            field=models.CharField(default='?', max_length=255),
        ),
    ]
