# Generated by Django 4.0.2 on 2022-02-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dados_id_alter_dados_id_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='Id_Sensor',
            new_name='Id_Sensor_id',
        ),
        migrations.AlterField(
            model_name='dados',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
