# Generated by Django 4.0.2 on 2022-02-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dados_remove_sensor_data_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='Sexo',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Sexo',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
