# Generated by Django 4.0.2 on 2022-02-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_sensor_dados_id_sensor_id_alter_dados_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='telefone',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
