# Generated by Django 4.0.2 on 2022-02-14 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medico_telefone_paciente_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacoes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(blank=True, max_length=255)),
                ('Id_Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
            ],
        ),
    ]
